export const LOCATION_DATA = {
    "Miền Bắc": {
        "Hà Nội": ["Quận Cầu Giấy", "Quận Ba Đình", "Quận Đống Đa", "Quận Hai Bà Trưng", "Quận Hoàn Kiếm", "Quận Tây Hồ", "Quận Long Biên"],
        "Hải Phòng": ["Quận Hồng Bàng", "Quận Lê Chân", "Quận Ngô Quyền", "Quận Hải An", "Huyện Thủy Nguyên"],
        "Hải Dương": ["Thành phố Hải Dương", "Thành phố Chí Linh", "Thị xã Kinh Môn"],
        "Bắc Ninh": ["Thành phố Bắc Ninh", "Thành phố Từ Sơn", "Huyện Quế Võ"],
        "Vĩnh Phúc": ["Thành phố Vĩnh Yên", "Thành phố Phúc Yên", "Huyện Bình Xuyên"],
        "Hưng Yên": ["Thành phố Hưng Yên", "Thị xã Mỹ Hào", "Huyện Văn Lâm"],
        "Thái Bình": ["Thành phố Thái Bình", "Huyện Tiền Hải", "Huyện Đông Hưng"],
        "Nam Định": ["Thành phố Nam Định", "Huyện Hải Hậu", "Huyện Giao Thủy"],
        "Hà Nam": ["Thành phố Phủ Lý", "Thị xã Duy Tiên"],
        "Ninh Bình": ["Thành phố Ninh Bình", "Thành phố Tam Điệp"],
        "Quảng Ninh": ["Thành phố Hạ Long", "Thành phố Cẩm Phả", "Thành phố Móng Cái", "Thành phố Uông Bí"],
        "Phú Thọ": ["Thành phố Việt Trì", "Thị xã Phú Thọ"],
        "Bắc Giang": ["Thành phố Bắc Giang", "Huyện Việt Yên", "Huyện Lạng Giang"],
        "Hòa Bình": ["Thành phố Hòa Bình", "Huyện Lương Sơn"],
        "Thái Nguyên": ["Thành phố Thái Nguyên", "Thành phố Sông Công", "Thành phố Phổ Yên"],
        "Lạng Sơn": ["Thành phố Lạng Sơn", "Huyện Hữu Lũng"],
        "Tuyên Quang": ["Thành phố Tuyên Quang"],
        "Yên Bái": ["Thành phố Yên Bái", "Thị xã Nghĩa Lộ"],
        "Lào Cai": ["Thành phố Lào Cai", "Thị xã Sa Pa"],
        "Điện Biên": ["Thành phố Điện Biên Phủ", "Thị xã Mường Lay"],
        "Lai Châu": ["Thành phố Lai Châu"],
        "Sơn La": ["Thành phố Sơn La", "Huyện Mộc Châu"],
        "Hà Giang": ["Thành phố Hà Giang"],
        "Cao Bằng": ["Thành phố Cao Bằng"],
        "Bắc Kạn": ["Thành phố Bắc Kạn"]
    },
    "Miền Trung": {
        "Đà Nẵng": ["Quận Hải Châu", "Quận Thanh Khê", "Quận Sơn Trà", "Quận Ngũ Hành Sơn", "Quận Liên Chiểu", "Quận Cẩm Lệ"],
        "Thanh Hóa": ["Thành phố Thanh Hóa", "Thành phố Sầm Sơn", "Thị xã Bỉm Sơn", "Thị xã Nghi Sơn"],
        "Nghệ An": ["Thành phố Vinh", "Thị xã Cửa Lò", "Thị xã Thái Hòa"],
        "Hà Tĩnh": ["Thành phố Hà Tĩnh", "Thị xã Hồng Lĩnh", "Thị xã Kỳ Anh"],
        "Quảng Bình": ["Thành phố Đồng Hới", "Thị xã Ba Đồn"],
        "Quảng Trị": ["Thành phố Đông Hà", "Thị xã Quảng Trị"],
        "Thừa Thiên Huế": ["Thành phố Huế", "Thị xã Hương Thủy", "Thị xã Hương Trà"],
        "Quảng Nam": ["Thành phố Tam Kỳ", "Thành phố Hội An", "Thị xã Điện Bàn"],
        "Quảng Ngãi": ["Thành phố Quảng Ngãi", "Thị xã Đức Phổ"],
        "Bình Định": ["Thành phố Quy Nhơn", "Thị xã An Nhơn", "Thị xã Hoài Nhơn"],
        "Phú Yên": ["Thành phố Tuy Hòa", "Thị xã Sông Cầu", "Thị xã Đông Hòa"],
        "Khánh Hòa": ["Thành phố Nha Trang", "Thành phố Cam Ranh", "Thị xã Ninh Hòa"],
        "Ninh Thuận": ["Thành phố Phan Rang - Tháp Chàm"],
        "Bình Thuận": ["Thành phố Phan Thiết", "Thị xã La Gi"],
        "Kon Tum": ["Thành phố Kon Tum"],
        "Gia Lai": ["Thành phố Pleiku", "Thị xã An Khê", "Thị xã Ayun Pa"],
        "Đắk Lắk": ["Thành phố Buôn Ma Thuột", "Thị xã Buôn Hồ"],
        "Đắk Nông": ["Thành phố Gia Nghĩa"],
        "Lâm Đồng": ["Thành phố Đà Lạt", "Thành phố Bảo Lộc"]
    },
    "Miền Nam": {
        "TP. Hồ Chí Minh": ["Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 10", "Quận 11", "Quận 12", "Quận Bình Tân", "Quận Bình Thạnh", "Quận Gò Vấp", "Quận Phú Nhuận", "Quận Tân Bình", "Quận Tân Phú", "Thành phố Thủ Đức", "Huyện Bình Chánh", "Huyện Cần Giờ", "Huyện Củ Chi", "Huyện Hóc Môn", "Huyện Nhà Bè"],
        "Bình Dương": ["Thành phố Thủ Dầu Một", "Thành phố Thuận An", "Thành phố Dĩ An", "Thành phố Tân Uyên", "Thành phố Bến Cát"],
        "Đồng Nai": ["Thành phố Biên Hòa", "Thành phố Long Khánh", "Huyện Long Thành", "Huyện Nhơn Trạch"],
        "Bà Rịa - Vũng Tàu": ["Thành phố Vũng Tàu", "Thành phố Bà Rịa", "Thị xã Phú Mỹ"],
        "Long An": ["Thành phố Tân An", "Thị xã Kiến Tường", "Huyện Đức Hòa", "Huyện Cần Giuộc"],
        "Tiền Giang": ["Thành phố Mỹ Tho", "Thị xã Gò Công", "Thị xã Cai Lậy"],
        "Bến Tre": ["Thành phố Bến Tre"],
        "Trà Vinh": ["Thành phố Trà Vinh"],
        "Vĩnh Long": ["Thành phố Vĩnh Long", "Thị xã Bình Minh"],
        "Đồng Tháp": ["Thành phố Cao Lãnh", "Thành phố Sa Đéc", "Thành phố Hồng Ngự"],
        "An Giang": ["Thành phố Long Xuyên", "Thành phố Châu Đốc", "Thị xã Tân Châu", "Thị xã Tịnh Biên"],
        "Kiên Giang": ["Thành phố Rạch Giá", "Thành phố Hà Tiên", "Thành phố Phú Quốc"],
        "Cần Thơ": ["Quận Ninh Kiều", "Quận Bình Thủy", "Quận Cái Răng", "Quận Thốt Nốt", "Quận Ô Môn"],
        "Hậu Giang": ["Thành phố Vị Thanh", "Thành phố Ngã Bảy", "Thị xã Long Mỹ"],
        "Sóc Trăng": ["Thành phố Sóc Trăng", "Thị xã Vĩnh Châu", "Thị xã Ngã Năm"],
        "Bạc Liêu": ["Thành phố Bạc Liêu", "Thị xã Giá Rai"],
        "Cà Mau": ["Thành phố Cà Mau"],
        "Tây Ninh": ["Thành phố Tây Ninh", "Thị xã Hòa Thành", "Thị xã Trảng Bàng"],
        "Bình Phước": ["Thành phố Đồng Xoài", "Thị xã Phước Long", "Thị xã Bình Long", "Thị xã Chơn Thành"]
    }
};

export type RegionKey = keyof typeof LOCATION_DATA;